# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC04AUTOMATED():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC04AUTOMATED(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1296, 688)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("xapewij851@keshitv.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("hola123")
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "itemImage").click()
    
    #assert
    imagen = self.driver.find_element (By.CLASS_NAME, "itemImage").text
    assert "Sample" in imagen

    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    self.driver.find_element(By.LINK_TEXT, "CART 2").click()
    self.driver.find_element(By.LINK_TEXT, "Proceed to checkout").click()
  
